version: '3.8'

services:
  my-go-app:
    container_name: my-go-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      MONGO_URL: "mongodb+srv://vinayakrajqaz:2D21NHXScPrOMp2p@cluster0.gucjl.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
    restart: always
