apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-go-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-go-app
  template:
    metadata:
      labels:
        app: my-go-app
    spec:
      containers:
      - name: my-go-app
        image: g0_project_my-go-app:latest
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_URL
          value: "mongodb+srv://vinayakrajqaz:2D21NHXScPrOMp2p@cluster0.gucjl.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
